ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS channel TEXT DEFAULT 'webhook';
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS priority INT DEFAULT 0;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS fallback_channel INT;